# Experiment 2: NumPy Arrays

**Task 1: Creating and Manipulating NumPy Arrays**

Write a Python program to create a NumPy array and perform basic operations such as:

1. Indexing
2. Slicing
3. Reshaping

In [1]:
# IMPORT the NUMPY LIBRARY

import numpy as np

In [2]:
# Create a NumPy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original Array:", array)

Original Array: [ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# Indexing: Access the first element
first_element = array[0]
print("First Element:", first_element)

First Element: 1


In [4]:
# Slicing: Access elements from index 2 to 5
sliced_array = array[2:6]
print("Sliced Array (index 2 to 5):", sliced_array)

Sliced Array (index 2 to 5): [3 4 5 6]


In [5]:
# Reshaping: Reshape the array to 2x5
reshaped_array = array.reshape(2, 5)
print("Reshaped Array (2x5):\n", reshaped_array)

Reshaped Array (2x5):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


---

**Task 2: Array Operations**
    
Write a Python program to perform various arithmetic operations like:

1. Addition
2. Subtraction
3. Multiplication
4. Division

In [9]:
# Create two NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])
print("array1 =", array1)
print("array2 =", array2)

array1 = [1 2 3 4 5]
array2 = [5 4 3 2 1]


In [10]:
# Addition
sum_array = array1 + array2
print("Sum of Arrays:", sum_array)

Sum of Arrays: [6 6 6 6 6]


In [11]:
# Subtraction
diff_array = array1 - array2
print("Difference of Arrays:", diff_array)

Difference of Arrays: [-4 -2  0  2  4]


In [12]:
# Multiplication
prod_array = array1 * array2
print("Product of Arrays:", prod_array)

Product of Arrays: [5 8 9 8 5]


In [13]:
# Division
div_array = array1 / array2
print("Division of Arrays:", div_array)

Division of Arrays: [0.2 0.5 1.  2.  5. ]


---

**Task 3: Universal Functions (ufuncs)**

Write a Python program to demonstrate the use of universal functions such as:

1. Square root
2. Exponential
3. Trigonometric
4. Logarithmic


In [14]:
# Create a NumPy array
array = np.array([1, 4, 9, 16, 25])
print(array)

[ 1  4  9 16 25]


In [15]:
# Square root
sqrt_array = np.sqrt(array)
print("Square Root of Array:", sqrt_array)

Square Root of Array: [1. 2. 3. 4. 5.]


In [16]:
# Exponential
exp_array = np.exp(array)
print("Exponential of Array:", exp_array)

Exponential of Array: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]


In [17]:
# Sine
sin_array = np.sin(array)
print("Sine of Array:", sin_array)

Sine of Array: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]


In [18]:
# Logarithm
log_array = np.log(array)
print("Logarithm of Array:", log_array)

Logarithm of Array: [0.         1.38629436 2.19722458 2.77258872 3.21887582]


---

**Task 4: Statistical Operations**

Write a Python program to perform statistical operations such as:

1. Mean
2. Median
3. Standard Deviation
4. Sum


In [19]:
# Create a NumPy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
# Mean
mean_value = np.mean(array)
print("Mean:", mean_value)

Mean: 5.5


In [21]:
# Median
median_value = np.median(array)
print("Median:", median_value)

Median: 5.5


In [22]:
# Standard Deviation
std_dev = np.std(array)
print("Standard Deviation:", std_dev)

Standard Deviation: 2.8722813232690143


In [23]:
# Sum
sum_value = np.sum(array)
print("Sum:", sum_value)

Sum: 55


---

**Task 5: Broadcasting and Vectorized Operations**

Write a Python program to demonstrate broadcasting and vectorized operations in NumPy.


In [24]:
# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])
print(array)

[1 2 3 4 5]


In [25]:
# Broadcasting: Add a scalar to each element
broadcasted_array = array + 10
print("Broadcasted Array (Add 10):", broadcasted_array)

Broadcasted Array (Add 10): [11 12 13 14 15]


In [26]:
# Vectorized Operation: Element-wise multiplication
vectorized_array = array * 2
print("Vectorized Array (Multiply by 2):", vectorized_array)

Vectorized Array (Multiply by 2): [ 2  4  6  8 10]
